### ISSUE TITLE
Don't change `flycheck-mode-line` when loading

### ISSUE THREAD

**Issue by swsnr** [liblit/flycheck-status-emoji#1]
Please don't call `(setq flycheck-mode-line …)` on top level.  Having side effecting forms on top level is bad style, as it becomes impossible to safely `load` a package.

Instead, either add the form to your README, or provide a function or minor mode for the user to setup your package.

**Comment by liblit** [comment]
A global minor mode sounds appropriate here. I will make it happen. Thank you for the suggestion!
