### ISSUE TITLE
Suggest making the emoji for each state more distinct

### ISSUE THREAD

**Issue by rochg** [liblit/flycheck-status-emoji#2]
Hi! Thanks very much for this module. Our team has added it to our Emacs config recently and it helps make the status clearer and save space on the mode line. It's also given us a good laugh!

One suggestion. When we adopted the module, I edited it locally so that the emoji for each state were more distinct. With the original emoji I found I was having to squint at the mode line to be sure exactly what the state was. I wanted the state to be more obvious at a glance.

So, I used:

😎(Smiling face with sunglasses) for when everything is good
😢(Crying face) for warnings
💀(Skull) for errors
💤(Sleeping symbol) for when flyc is busy

Wondering if you'd like to adopt these or at least make the choice of emoji configurable?

This is on an a Mac with the "Apple Color Emoji" font - appreciate that they may be more distinct in some other fonts.

Thanks again!

**Comment by liblit** [comment]
Thanks for the kind words and suggested improvement! To me, “💤” suggests being idle, not busy. But reasonable people can disagree, so customization is clearly the right approach. You can give that a try in the latest master revision. Look for customization variables whose names start with `flycheck-status-emoji-indicator-`.

Please add a comment here to let me know if this works well and suits your needs. If it does, I will then tag an official 1.2 release with this new feature.

**Comment by rochg** [comment]
Thanks so much for the quick update.

Yes, it works perfectly - have replaced my local code with the new version and set the custom variables with e.g.

(custom-set-variables
 '(flycheck-status-emoji-indicator-finished-ok ?😎)
)

If you're able to tag an official release that would be great and I can delete my local copy and go back to picking up a package-install version.

Personally, I would still think it may be worth considering making the defaults more distinct, but I appreciate that's a matter of opinion. The customization solution works perfectly.

Cheers!

**Comment by liblit** [comment]
Released as [version 1.2](https://github.com/liblit/flycheck-status-emoji/releases/tag/1.2).
