### ISSUE TITLE
Mode line doesn't change after enabling

### ISSUE THREAD

**Issue by greenrd** [liblit/flycheck-status-emoji#3]
After I do `M-x flycheck-status-emoji-mode`, the message `Flycheck-Status-Emoji mode enabled` is displayed, but nothing happens to the modeline, it still displays Flycheck results in the old way, using text and no emoji - even when I create a new file. I have installed the requisite font.

I am using

```
GNU Emacs 24.5.1 (x86_64-redhat-linux-gnu, GTK+ Version 3.18.7)
 of 2016-02-03 on buildhw-05.phx2.fedoraproject.org
```

**Comment by liblit** [comment]
Interesting. `flycheck-status-emoji` falls back on standard `flycheck` indicators if the requested emoji are not displayable. So my first hunch is that the font may not be installed properly, or may be unknown to Emacs. Please load up the `flycheck-status-emoji.el` source file in an Emacs buffer. Starting around [line 60](https://github.com/liblit/flycheck-status-emoji/blob/master/flycheck-status-emoji.el#L60) you should see several `defcustom` declarations, each including a single emoji character after a question mark, such as:

``` elisp
(defcustom flycheck-status-emoji-indicator-running ?😔 ...)
```

Do you see a proper “😔” emoji after the question mark?

<hr/>

If the emoji look fine in that file, then the next possibility is that `flycheck-status-emoji` failed to insert its code into the `flycheck` mode-line lighter. After you turn on `flycheck-status-emoji-mode`, what is the value of `flycheck-mode-line`? Use `C-h v flycheck-mode-line` to check this. The first few lines of the resulting help buffer should be:

```
flycheck-mode-line is a variable defined in `flycheck.el'.
Its value is (:eval (flycheck-status-emoji-mode-line-text))
Original value was 
(:eval
 (flycheck-mode-line-status-text))
```

Is that what you see? If not, what do you have there instead?

**Comment by greenrd** [comment]
No, the emoji doesn't show up on line 60.

**Comment by liblit** [comment]
Then you do not have a suitable emoji font installed, or it is installed but unknown to Emacs. Simply installing Symbola as [recommended at the end of the `README`](https://github.com/liblit/flycheck-status-emoji/blob/master/README.md#dependencies) is not enough; you also need to tell Emacs when and where to use that font. Based on [advice from the Endless Parentheses blog](http://endlessparentheses.com/manually-choose-a-fallback-font-for-unicode.html), I find that adding `(set-fontset-font t nil "Symbola")` to my Emacs startup code works well. Does that help you too? If you tell me that it does, I will add that advice to the `README` too in case others have the same problem.

**Comment by greenrd** [comment]
Yes, it does - `C-x C-e` on that new line immediately fixed the problem - thanks!

**Comment by liblit** [comment]
Excellent! Thanks for working with me to figure this out. I will add some helpful hints to [the fonts text in the README](https://github.com/liblit/flycheck-status-emoji/blob/master/README.md#dependencies).
